---
kind: "operation"
client: "atomist-bot"
generator:
  name: "NewSpringBootRestService"
  group: "atomist-rugs"
  artifact: "spring-boot-rest-service"
  version: "0.9.0"
  origin:
    repo: "https://github.com/atomist-rugs/spring-boot-rest-service.git"
    branch: "bbeb8db6235597154ebdd20a7d9c4bdb924b5b33"
    sha: "bbeb8db"
  parameters:
    - "project_name": "TestRug"
    - "artifactId": "myartifact"
    - "groupId": "mygroup"
    - "version": "0.1.0-SNAPSHOT"
    - "description": "My new project"
    - "rootPackage": "com.myorg"
    - "serviceClassName": "Test"

